;; SRFI-175 (ASCII character library) conformance tests
;; Run: zig-out/bin/kaappi tests/scheme/srfi/srfi175.scm

(import (scheme base) (scheme write) (scheme process-context) (srfi 64) (srfi 175))

(test-begin "srfi-175")

;;; --- ascii-codepoint? ---
(test-equal "codepoint? 0" #t (ascii-codepoint? 0))
(test-equal "codepoint? 127" #t (ascii-codepoint? 127))
(test-equal "codepoint? 128" #f (ascii-codepoint? 128))
(test-equal "codepoint? -1" #f (ascii-codepoint? -1))
(test-equal "codepoint? inexact" #f (ascii-codepoint? 65.0))
(test-equal "codepoint? symbol" #f (ascii-codepoint? 'a))

;;; --- ascii-bytevector? ---
(test-equal "bytevector? all-ascii" #t (ascii-bytevector? #u8(0 65 127)))
(test-equal "bytevector? empty" #t (ascii-bytevector? #u8()))
(test-equal "bytevector? non-ascii" #f (ascii-bytevector? #u8(0 128)))
(test-equal "bytevector? not-bv" #f (ascii-bytevector? "hello"))

;;; --- ascii-char? / ascii-string? ---
(test-equal "char? a" #t (ascii-char? #\a))
(test-equal "char? delete" #t (ascii-char? #\delete))
(test-equal "char? lambda" #f (ascii-char? #\λ))
(test-equal "char? integer" #f (ascii-char? 65))
(test-equal "string? hello" #t (ascii-string? "hello"))
(test-equal "string? empty" #t (ascii-string? ""))
(test-equal "string? non-ascii" #f (ascii-string? "aλb"))
(test-equal "string? not-string" #f (ascii-string? 42))

;;; --- classification predicates ---
(test-equal "control? null" #t (ascii-control? #\null))
(test-equal "control? delete" #t (ascii-control? #\delete))
(test-equal "control? a" #f (ascii-control? #\a))
(test-equal "control? int 7" #t (ascii-control? 7))
(test-equal "non-control? space" #t (ascii-non-control? #\space))
(test-equal "non-control? tab" #f (ascii-non-control? #\tab))
(test-equal "space-or-tab? space" #t (ascii-space-or-tab? #\space))
(test-equal "space-or-tab? tab" #t (ascii-space-or-tab? #\tab))
(test-equal "space-or-tab? newline" #f (ascii-space-or-tab? #\newline))
(test-equal "whitespace? newline" #t (ascii-whitespace? #\newline))
(test-equal "whitespace? space" #t (ascii-whitespace? #\space))
(test-equal "whitespace? cr" #t (ascii-whitespace? 13))
(test-equal "whitespace? a" #f (ascii-whitespace? #\a))
(test-equal "other-graphic? !" #t (ascii-other-graphic? #\!))
(test-equal "other-graphic? @" #t (ascii-other-graphic? #\@))
(test-equal "other-graphic? a" #f (ascii-other-graphic? #\a))
(test-equal "other-graphic? 5" #f (ascii-other-graphic? #\5))
(test-equal "alphabetic? a" #t (ascii-alphabetic? #\a))
(test-equal "alphabetic? Z" #t (ascii-alphabetic? #\Z))
(test-equal "alphabetic? 5" #f (ascii-alphabetic? #\5))
(test-equal "numeric? 5" #t (ascii-numeric? #\5))
(test-equal "numeric? a" #f (ascii-numeric? #\a))
(test-equal "alphanumeric? a" #t (ascii-alphanumeric? #\a))
(test-equal "alphanumeric? 5" #t (ascii-alphanumeric? #\5))
(test-equal "alphanumeric? _" #f (ascii-alphanumeric? #\_))
(test-equal "upper-case? A" #t (ascii-upper-case? #\A))
(test-equal "upper-case? a" #f (ascii-upper-case? #\a))
(test-equal "lower-case? z" #t (ascii-lower-case? #\z))
(test-equal "lower-case? Z" #f (ascii-lower-case? #\Z))

;;; --- case conversion ---
(test-equal "upcase a" #\A (ascii-upcase #\a))
(test-equal "upcase A" #\A (ascii-upcase #\A))
(test-equal "upcase 5" #\5 (ascii-upcase #\5))
(test-equal "upcase int" 65 (ascii-upcase 97))
(test-equal "downcase A" #\a (ascii-downcase #\A))
(test-equal "downcase a" #\a (ascii-downcase #\a))
(test-equal "downcase int" 97 (ascii-downcase 65))

;;; --- case-insensitive character comparison ---
(test-equal "ci=? a A" #t (ascii-ci=? #\a #\A))
(test-equal "ci=? A a" #t (ascii-ci=? #\A #\a))
(test-equal "ci=? a b" #f (ascii-ci=? #\a #\b))
(test-equal "ci=? int" #t (ascii-ci=? 65 97))
(test-equal "ci<? a B" #t (ascii-ci<? #\a #\B))
(test-equal "ci<? b A" #f (ascii-ci<? #\b #\A))
(test-equal "ci>? b A" #t (ascii-ci>? #\b #\A))
(test-equal "ci>? a B" #f (ascii-ci>? #\a #\B))
(test-equal "ci<=? a A" #t (ascii-ci<=? #\a #\A))
(test-equal "ci<=? a B" #t (ascii-ci<=? #\a #\B))
(test-equal "ci<=? b A" #f (ascii-ci<=? #\b #\A))
(test-equal "ci>=? a A" #t (ascii-ci>=? #\a #\A))
(test-equal "ci>=? b A" #t (ascii-ci>=? #\b #\A))
(test-equal "ci>=? a B" #f (ascii-ci>=? #\a #\B))

;;; --- case-insensitive string comparison ---
(test-equal "string-ci=? same" #t (ascii-string-ci=? "Hello" "hello"))
(test-equal "string-ci=? diff" #f (ascii-string-ci=? "Hello" "world"))
(test-equal "string-ci=? empty" #t (ascii-string-ci=? "" ""))
(test-equal "string-ci=? length" #f (ascii-string-ci=? "ab" "abc"))
(test-equal "string-ci<? yes" #t (ascii-string-ci<? "abc" "DEF"))
(test-equal "string-ci<? no" #f (ascii-string-ci<? "def" "ABC"))
(test-equal "string-ci<? prefix" #t (ascii-string-ci<? "ab" "ABC"))
(test-equal "string-ci>? yes" #t (ascii-string-ci>? "def" "ABC"))
(test-equal "string-ci>? no" #f (ascii-string-ci>? "abc" "DEF"))
(test-equal "string-ci<=? eq" #t (ascii-string-ci<=? "ABC" "abc"))
(test-equal "string-ci<=? lt" #t (ascii-string-ci<=? "abc" "DEF"))
(test-equal "string-ci>=? eq" #t (ascii-string-ci>=? "ABC" "abc"))
(test-equal "string-ci>=? gt" #t (ascii-string-ci>=? "def" "ABC"))

;;; --- control <-> graphic ---
(test-equal "control->graphic NUL" #\@ (ascii-control->graphic #\null))
(test-equal "control->graphic BEL" #\G (ascii-control->graphic (integer->char 7)))
(test-equal "control->graphic DEL" #\? (ascii-control->graphic #\delete))
(test-equal "control->graphic ESC" #\[ (ascii-control->graphic #\escape))
(test-equal "control->graphic non-ctrl" #f (ascii-control->graphic #\a))
(test-equal "control->graphic int 0" 64 (ascii-control->graphic 0))
(test-equal "control->graphic int 127" 63 (ascii-control->graphic 127))
(test-equal "graphic->control @" #\null (ascii-graphic->control #\@))
(test-equal "graphic->control G" (integer->char 7) (ascii-graphic->control #\G))
(test-equal "graphic->control ?" #\delete (ascii-graphic->control #\?))
(test-equal "graphic->control [" #\escape (ascii-graphic->control #\[))
(test-equal "graphic->control non-map" #f (ascii-graphic->control #\a))
(test-equal "graphic->control int 64" 0 (ascii-graphic->control 64))

;;; --- mirror bracket ---
(test-equal "mirror (" #\) (ascii-mirror-bracket #\())
(test-equal "mirror )" #\( (ascii-mirror-bracket #\)))
(test-equal "mirror [" #\] (ascii-mirror-bracket #\[))
(test-equal "mirror ]" #\[ (ascii-mirror-bracket #\]))
(test-equal "mirror {" #\} (ascii-mirror-bracket #\{))
(test-equal "mirror }" #\{ (ascii-mirror-bracket #\}))
(test-equal "mirror <" #\> (ascii-mirror-bracket #\<))
(test-equal "mirror >" #\< (ascii-mirror-bracket #\>))
(test-equal "mirror non-bracket" #f (ascii-mirror-bracket #\a))
(test-equal "mirror int 40" 41 (ascii-mirror-bracket 40))

;;; --- digit-value (FIXED: only decimal digits 0-9) ---
(test-equal "digit-value 7 base10" 7 (ascii-digit-value #\7 10))
(test-equal "digit-value 0 base10" 0 (ascii-digit-value #\0 10))
(test-equal "digit-value 7 base7" #f (ascii-digit-value #\7 7))
(test-equal "digit-value 1 base2" 1 (ascii-digit-value #\1 2))
(test-equal "digit-value space" #f (ascii-digit-value #\space 10))
;; Regression for #1236: letters must return #f
(test-equal "digit-value a base16" #f (ascii-digit-value #\a 16))
(test-equal "digit-value F base16" #f (ascii-digit-value #\F 16))
(test-equal "digit-value A base36" #f (ascii-digit-value #\A 36))
(test-equal "digit-value int 48" 0 (ascii-digit-value 48 10))

;;; --- upper/lower-case-value ---
(test-equal "upper-case-value C" 12 (ascii-upper-case-value #\C 10 26))
(test-equal "upper-case-value A" 0 (ascii-upper-case-value #\A 0 26))
(test-equal "upper-case-value Z limit" #f (ascii-upper-case-value #\Z 0 25))
(test-equal "upper-case-value lowercase" #f (ascii-upper-case-value #\a 0 26))
(test-equal "lower-case-value c" 12 (ascii-lower-case-value #\c 10 26))
(test-equal "lower-case-value uppercase" #f (ascii-lower-case-value #\A 0 26))

;;; --- nth constructors ---
(test-equal "nth-digit 0" #\0 (ascii-nth-digit 0))
(test-equal "nth-digit 9" #\9 (ascii-nth-digit 9))
(test-equal "nth-digit -1" #f (ascii-nth-digit -1))
(test-equal "nth-digit 10" #f (ascii-nth-digit 10))
(test-equal "nth-upper 0" #\A (ascii-nth-upper-case 0))
(test-equal "nth-upper 25" #\Z (ascii-nth-upper-case 25))
(test-equal "nth-upper 26 wraps" #\A (ascii-nth-upper-case 26))
(test-equal "nth-lower 0" #\a (ascii-nth-lower-case 0))
(test-equal "nth-lower 25" #\z (ascii-nth-lower-case 25))
(test-equal "nth-lower 26 wraps" #\a (ascii-nth-lower-case 26))

(let ((runner (test-runner-current)))
  (test-end "srfi-175")
  (when (> (test-runner-fail-count runner) 0) (exit 1)))
