;; SRFI-143 (fixnums) conformance tests — audit Phase 3c
;; Run directly: zig-out/bin/kaappi tests/scheme/srfi/srfi143.scm

(import (scheme base) (srfi 143) (scheme process-context) (srfi 64))

(test-begin "srfi-143")

;;; --- constants and fixnum? ---
(test-equal #t (>= fx-width 14))                       ; SRFI-143 minimum
(test-equal #t (= fx-greatest (- (expt 2 (- fx-width 1)) 1)))
(test-equal #t (= fx-least (- (expt 2 (- fx-width 1)))))
(test-equal #t (fixnum? 0))
(test-equal #t (fixnum? fx-greatest))
(test-equal #t (fixnum? fx-least))
(test-equal #f (fixnum? (+ fx-greatest 1)))
(test-equal #f (fixnum? 1.0))
(test-equal #f (fixnum? 1/2))
(test-equal #f (fixnum? 'a))

;;; --- comparisons ---
(test-equal #t (fx=? 1 1))
(test-equal #t (fx<? 1 2))
(test-equal #f (fx<? 2 1))
(test-equal #t (fx>? 3 2))
(test-equal #t (fx<=? 1 1))
(test-equal #t (fx>=? 2 2))
(test-equal #t (fx<? 1 2 3))
(test-equal #f (fx<? 1 3 2))
(test-equal #t (fx>? 3 2 1))
(test-equal #f (fx>? 3 1 2))
(test-equal #t (fx=? 5 5 5))
(test-equal #f (fx=? 5 5 6))
(test-equal #t (fx<=? 1 1 2 3))
(test-equal #f (fx<=? 1 3 2))
(test-equal #t (fx>=? 3 2 2 1))

;;; --- predicates ---
(test-equal #t (fxzero? 0))
(test-equal #f (fxzero? 1))
(test-equal #t (fxpositive? 1))
(test-equal #f (fxpositive? 0))
(test-equal #t (fxnegative? -1))
(test-equal #t (fxodd? 3))
(test-equal #t (fxeven? 4))
(test-equal #f (fxeven? 3))

;;; --- arithmetic ---
(test-equal 5 (fx+ 2 3))
(test-equal -1 (fx- 2 3))
(test-equal 6 (fx* 2 3))
(test-equal -2 (fxneg 2))
(test-equal 3 (fxquotient 7 2))
(test-equal -3 (fxquotient -7 2))
(test-equal 1 (fxremainder 7 2))
(test-equal -1 (fxremainder -7 2))
(test-equal 5 (fxabs -5))
(test-equal 9 (fxsquare 3))
(test-equal 3 (fxmax 1 3))
(test-equal 1 (fxmin 2 1))
(test-equal 3 (fxmax 1 3 2))
(test-equal 1 (fxmin 2 1 3))
(test-equal 5 (fxmax 5))
(test-equal 5 (fxmin 5))
(test-equal 4 (fxmax 1 4 2 3))

;;; --- bitwise ---
(test-equal 10 (fxand 11 26))
(test-equal 8 (fxand -4 8))
(test-equal 5 (fxand -1 5))
(test-equal -8 (fxand -4 -6))
(test-equal 11 (fxior 3 10))
(test-equal -2 (fxior -4 2))
(test-equal 6 (fxxor 3 5))
(test-equal -6 (fxxor -1 5))
(test-equal -12 (fxxor -4 8))
(test-equal -11 (fxnot 10))
(test-equal 8 (fxarithmetic-shift 1 3))
(test-equal 2 (fxarithmetic-shift 16 -3))
(test-equal -1 (fxarithmetic-shift -1 -1))
(test-equal -4 (fxarithmetic-shift -15 -2))
(test-equal 8 (fxarithmetic-shift-left 1 3))
(test-equal 2 (fxarithmetic-shift-right 16 3))
(test-equal -4 (fxarithmetic-shift-right -7 1))
(test-equal 3 (fxbit-count 7))
(test-equal 1 (fxbit-count 8))
(test-equal 4 (fxlength 8))
(test-equal 0 (fxlength 0))
(test-equal 9 (fxif 3 1 8))
(test-equal #t (fxbit-set? 0 1))
(test-equal #f (fxbit-set? 1 1))
(test-equal #t (fxbit-set? 2 4))
(test-equal 2 (fxfirst-set-bit 12))
(test-equal -1 (fxfirst-set-bit 0))
(test-equal 0 (fxfirst-set-bit 1))
(test-equal 2 (fxbit-field 13 1 3))

(test-equal 4 (fxcopy-bit 2 0 #t))
(test-equal 1 (fxcopy-bit 2 5 #f))
(test-equal 0 (fxcopy-bit 0 0 #f))
(test-equal 1 (fxcopy-bit 0 0 #t))
(test-equal 5 (fxcopy-bit 0 5 #t))
(test-equal 4 (fxcopy-bit 0 5 #f))

(let ((runner (test-runner-current)))
  (test-end "srfi-143")
  (when (> (test-runner-fail-count runner) 0) (exit 1)))
