(import (scheme base) (scheme write) (scheme read) (scheme char) (srfi 13) (srfi 69))
(import (chibi test))

(test-begin "bugfixes")

;;; Fix 1: hash-table-ref calls default thunk (SRFI-69)
(let ((ht (make-hash-table)))
  (hash-table-set! ht 'a 1)
  (test 1 (hash-table-ref ht 'a (lambda () 99)))
  (test 99 (hash-table-ref ht 'missing (lambda () 99)))
  (test 42 (hash-table-ref ht 'missing (lambda () (* 6 7))))
  (test "default" (hash-table-ref ht 'missing "default"))
  (test 77 (hash-table-ref/default ht 'missing 77)))

;;; Fix 2: hash-table-merge! overwrites existing keys
(let ((ht1 (make-hash-table))
      (ht2 (make-hash-table)))
  (hash-table-set! ht1 'a 1)
  (hash-table-set! ht1 'b 2)
  (hash-table-set! ht2 'b 20)
  (hash-table-set! ht2 'c 30)
  (hash-table-merge! ht1 ht2)
  (test 1 (hash-table-ref ht1 'a))
  (test 20 (hash-table-ref ht1 'b))
  (test 30 (hash-table-ref ht1 'c))
  (test 3 (hash-table-size ht1)))

;;; Fix 3: #e prefix on floats produces rationals
(test 1 (read (open-input-string "#e1.0")))
(test 3/2 (read (open-input-string "#e1.5")))
(test 1/2 (read (open-input-string "#e0.5")))
(test 1/4 (read (open-input-string "#e0.25")))
(test -3/2 (read (open-input-string "#e-1.5")))
(test 42 (read (open-input-string "#e42")))
(test #t (exact? (read (open-input-string "#e1.5"))))
(test #t (exact? (read (open-input-string "#e0.5"))))
(test 42.0 (read (open-input-string "#i42")))
(test #t (inexact? (read (open-input-string "#i42"))))

;;; Fix 4: string-trim with predicate argument
(test "hello" (string-trim "  hello"))
(test "hello" (string-trim-right "hello  "))
(test "hello" (string-trim-both "  hello  "))
(test "hello" (string-trim "000hello" char-numeric?))
(test "hello" (string-trim-right "hello000" char-numeric?))
(test "hello" (string-trim-both "00hello00" char-numeric?))
(test "" (string-trim "xxxx" (lambda (c) (char=? c #\x))))
(test "" (string-trim-right "yyyy" (lambda (c) (char=? c #\y))))
(test "" (string-trim-both "zzzz" (lambda (c) (char=? c #\z))))
(test "hello" (string-trim "hello" char-numeric?))
(test "hello" (string-trim-right "hello" char-numeric?))
(test "hello" (string-trim-both "hello" char-numeric?))
(test "" (string-trim "" char-numeric?))
(test "" (string-trim-right "" char-numeric?))
(test "" (string-trim-both "" char-numeric?))

;;; Fix 5: FiberScheduler cleanup — verify fibers still work
(import (kaappi fibers))
(let ((f (spawn (lambda () (+ 21 21)))))
  (test 42 (fiber-join f)))
(let ((f1 (spawn (lambda () 10)))
      (f2 (spawn (lambda () 20))))
  (test 30 (+ (fiber-join f1) (fiber-join f2))))
(let ((ch (make-channel)))
  (let ((f (spawn (lambda () (channel-send ch 99)))))
    (test 99 (channel-receive ch))
    (fiber-join f)))

;;; Fix 6: define-values (confirmed working, regression test)
(define-values (dv-a dv-b dv-c) (values 10 20 30))
(test 10 dv-a)
(test 20 dv-b)
(test 30 dv-c)

(test-end "bugfixes")
