;; Audit tests for src/primitives_hashtable.zig — SRFI-69 hash tables.
;; Audit campaign Phase 2.11 (#1137).
;; Run directly and read the printed counts — run-all.sh only sees exit codes.

(import (scheme base) (scheme write) (srfi 69))
(import (chibi test))

(test-begin "primitives_hashtable audit")

;;; --- constructors and predicate ---
(test #t (hash-table? (make-hash-table)))
(test #f (hash-table? '((a . 1))))
(test #f (hash-table? #(1 2)))
(test 0 (hash-table-size (make-hash-table)))

;;; --- set! / ref / ref/default ---
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht 'k 'v)
           (hash-table-ref ht 'k)))
(test 'new (let ((ht (make-hash-table)))
             (hash-table-set! ht 'k 'old)
             (hash-table-set! ht 'k 'new)     ; overwrite, size stays 1
             (hash-table-ref ht 'k)))
(test 1 (let ((ht (make-hash-table)))
          (hash-table-set! ht 'k 'old)
          (hash-table-set! ht 'k 'new)
          (hash-table-size ht)))
(test 'from-thunk (hash-table-ref (make-hash-table) 'missing (lambda () 'from-thunk)))
(test 'dflt (hash-table-ref/default (make-hash-table) 'missing 'dflt))
(test 'caught (guard (e (#t 'caught)) (hash-table-ref (make-hash-table) 'missing)))
(test 'caught (guard (e (#t 'caught))
                (hash-table-ref (make-hash-table) 'missing (lambda () (error "boom")))))
(test 'caught (guard (e (#t 'caught)) (hash-table-ref '((a . 1)) 'a)))
(test 'caught (guard (e (#t 'caught)) (hash-table-set! "not-ht" 'k 'v)))

;;; --- key type coverage: hash/equality must agree for immediates,
;;;     strings, symbols, chars, and shallow structures ---
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht "key" 'v)
           (hash-table-ref/default ht (string-copy "key") 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht #\x 'v)
           (hash-table-ref/default ht #\x 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht 42 'v)
           (hash-table-ref/default ht 42 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht 1.5 'v)
           (hash-table-ref/default ht 1.5 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht #t 'v)
           (hash-table-ref/default ht #t 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht '() 'v)
           (hash-table-ref/default ht '() 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht (list 1 2) 'v)
           (hash-table-ref/default ht (list 1 2) 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht (vector 1 "a") 'v)
           (hash-table-ref/default ht (vector 1 "a") 'missing)))
(test 'v (let ((ht (make-hash-table)))
           (hash-table-set! ht (bytevector 1 2) 'v)
           (hash-table-ref/default ht (bytevector 1 2) 'missing)))
;; Heap-boxed numeric keys hash by pointer while lookup compares by equal? —
;; entries become unfindable once the table grows past one bucket-group
;; (verified: 27/30 bignum and 28/30 rational lookups miss at 30 entries).
;; Same class: pairs/vectors nested deeper than the depth-8 hash cutoff.
;; FAIL: #1180 (bignum/rational/complex and deep structural keys are unfindable)
;; (test 0 (let ((ht (make-hash-table)))
;;           (do ((i 0 (+ i 1))) ((= i 30))
;;             (hash-table-set! ht (+ (expt 2 100) i) i))
;;           (let ((misses 0))
;;             (do ((i 0 (+ i 1))) ((= i 30))
;;               (if (eq? 'missing (hash-table-ref/default ht (+ (expt 2 100) i) 'missing))
;;                   (set! misses (+ misses 1))))
;;             misses)))
;; (test 0 (let ((ht (make-hash-table)))
;;           (do ((i 0 (+ i 1))) ((= i 30))
;;             (hash-table-set! ht (/ 1 (+ i 3)) i))
;;           (let ((misses 0))
;;             (do ((i 0 (+ i 1))) ((= i 30))
;;               (if (eq? 'missing (hash-table-ref/default ht (/ 1 (+ i 3)) 'missing))
;;                   (set! misses (+ misses 1))))
;;             misses)))

;;; --- growth: many entries stay findable (fixnum/string/symbol keys) ---
(test 0 (let ((ht (make-hash-table)))
          (do ((i 0 (+ i 1))) ((= i 100))
            (hash-table-set! ht i (* i i)))
          (let ((misses 0))
            (do ((i 0 (+ i 1))) ((= i 100))
              (if (not (equal? (* i i) (hash-table-ref/default ht i 'missing)))
                  (set! misses (+ misses 1))))
            misses)))
(test 100 (let ((ht (make-hash-table)))
            (do ((i 0 (+ i 1))) ((= i 100))
              (hash-table-set! ht i i))
            (hash-table-size ht)))

;;; --- exists? / delete! ---
(test #t (let ((ht (make-hash-table)))
           (hash-table-set! ht 'k 'v)
           (hash-table-exists? ht 'k)))
(test #f (hash-table-exists? (make-hash-table) 'k))
(test '(#f 0) (let ((ht (make-hash-table)))
                (hash-table-set! ht 'k 'v)
                (hash-table-delete! ht 'k)
                (list (hash-table-exists? ht 'k) (hash-table-size ht))))
;; deleting a missing key is a no-op
(test 1 (let ((ht (make-hash-table)))
          (hash-table-set! ht 'k 'v)
          (hash-table-delete! ht 'other)
          (hash-table-size ht)))
;; delete then re-insert (tombstone reuse)
(test 'v2 (let ((ht (make-hash-table)))
            (hash-table-set! ht 'k 'v1)
            (hash-table-delete! ht 'k)
            (hash-table-set! ht 'k 'v2)
            (hash-table-ref ht 'k)))

;;; --- keys / values / ->alist ---
(test '(a b) (let ((ht (make-hash-table)))
               (hash-table-set! ht 'a 1)
               (hash-table-set! ht 'b 2)
               (let ((ks (hash-table-keys ht)))
                 (if (memq 'a ks) (if (memq 'b ks) (list 'a 'b) 'missing-b) 'missing-a))))
(test 3 (let ((ht (make-hash-table)))
          (hash-table-set! ht 'a 1)
          (hash-table-set! ht 'b 2)
          (let loop ((vs (hash-table-values ht)) (sum 0))
            (if (null? vs) sum (loop (cdr vs) (+ sum (car vs)))))))
(test '((k . v)) (let ((ht (make-hash-table)))
                   (hash-table-set! ht 'k 'v)
                   (hash-table->alist ht)))
(test '() (hash-table->alist (make-hash-table)))

;;; --- alist->hash-table ---
(test 2 (hash-table-size (alist->hash-table '((a . 1) (b . 2)))))
;; SRFI-69: earlier associations take precedence
(test 1 (hash-table-ref (alist->hash-table '((k . 1) (k . 2))) 'k))
(test 0 (hash-table-size (alist->hash-table '())))
;; 12 entries (non-power-of-two count) all retrievable
(test '(12 12 1)
    (let ((ht (alist->hash-table '((a . 1) (b . 2) (c . 3) (d . 4) (e . 5) (f . 6)
                                  (g . 7) (h . 8) (i . 9) (j . 10) (k . 11) (l . 12)))))
      (list (hash-table-size ht)
            (hash-table-ref/default ht 'l 'missing)
            (hash-table-ref/default ht 'a 'missing))))
(test 'caught (guard (e (#t 'caught)) (alist->hash-table '(not-a-pair))))
(test 'caught (guard (e (#t 'caught)) (alist->hash-table 42)))

;;; --- walk / fold ---
(test 6 (let ((ht (make-hash-table)) (sum 0))
          (hash-table-set! ht 'a 1)
          (hash-table-set! ht 'b 2)
          (hash-table-set! ht 'c 3)
          (hash-table-walk ht (lambda (k v) (set! sum (+ sum v))))
          sum))
(test 6 (let ((ht (make-hash-table)))
          (hash-table-set! ht 'a 1)
          (hash-table-set! ht 'b 2)
          (hash-table-set! ht 'c 3)
          (hash-table-fold ht (lambda (k v acc) (+ acc v)) 0)))
(test 0 (hash-table-fold (make-hash-table) (lambda (k v acc) (+ acc 1)) 0))
(test 'caught (guard (e (#t 'caught))
                (let ((ht (make-hash-table)))
                  (hash-table-set! ht 'k 'v)
                  (hash-table-walk ht (lambda (k v) (error "boom"))))))
(test 'caught (guard (e (#t 'caught))
                (let ((ht (make-hash-table)))
                  (hash-table-set! ht 'k 'v)
                  (hash-table-fold ht (lambda (k v acc) (error "boom")) 0))))
;; mutation during walk: inserting during iteration must not crash;
;; all original entries are still visited (snapshot semantics)
(test 3 (let ((ht (make-hash-table)) (seen 0))
          (hash-table-set! ht 'a 1)
          (hash-table-set! ht 'b 2)
          (hash-table-set! ht 'c 3)
          (hash-table-walk ht (lambda (k v)
                                (hash-table-set! ht (list k) v)
                                (set! seen (+ seen 1))))
          seen))
;; The walk/fold snapshot is invisible to the GC: if the callback deletes
;; entries and allocates, the snapshot's keys/values are freed and reused,
;; and the callback receives corrupted pairs. Passes on a default build;
;; fails under -Dgc-stress=true (verified: 29/30 entries corrupted).
;; FAIL: #1181 (walk/fold snapshot unrooted — use-after-free under GC pressure)
;; (test '(435 0)
;;     (let ((ht (make-hash-table)) (sum 0) (bad 0))
;;       (do ((i 0 (+ i 1))) ((= i 30))
;;         (hash-table-set! ht (cons i 'key) (cons i 'val)))
;;       (hash-table-walk ht
;;         (lambda (k v)
;;           (do ((j 0 (+ j 1))) ((= j 30))
;;             (hash-table-delete! ht (cons j 'key)))
;;           (do ((j 0 (+ j 1))) ((= j 100))
;;             (cons j (make-vector 4 j)))
;;           (if (and (pair? k) (pair? v) (eq? (cdr k) 'key) (eq? (cdr v) 'val)
;;                    (= (car k) (car v)))
;;               (set! sum (+ sum (car k)))
;;               (set! bad (+ bad 1)))))
;;       (list sum bad)))

;;; --- update!/default ---
(test 11 (let ((ht (make-hash-table)))
           (hash-table-set! ht 'k 10)
           (hash-table-update!/default ht 'k (lambda (x) (+ x 1)) 0)
           (hash-table-ref ht 'k)))
(test 1 (let ((ht (make-hash-table)))
          (hash-table-update!/default ht 'k (lambda (x) (+ x 1)) 0)
          (hash-table-ref ht 'k)))
(test 'caught (guard (e (#t 'caught))
                (hash-table-update!/default (make-hash-table) 'k
                                            (lambda (x) (error "boom")) 0)))
;; SRFI-69 also specifies hash-table-update! (with optional failure thunk);
;; it is absent from (srfi 69) — only SRFI-125's Scheme lib defines one.
;; FAIL: #1182 (hash-table-update! missing from (srfi 69))
;; (test 11 (let ((ht (make-hash-table)))
;;            (hash-table-set! ht 'k 10)
;;            (hash-table-update! ht 'k (lambda (x) (+ x 1)))
;;            (hash-table-ref ht 'k)))

;;; --- copy / merge! ---
(test '(1 2) (let ((h1 (make-hash-table)))
               (hash-table-set! h1 'k 1)
               (let ((h2 (hash-table-copy h1)))
                 (hash-table-set! h2 'k 2)
                 (list (hash-table-ref h1 'k) (hash-table-ref h2 'k)))))
(test 'new (let ((h1 (make-hash-table)) (h2 (make-hash-table)))
             (hash-table-set! h1 'k 'old)
             (hash-table-set! h2 'k 'new)
             (hash-table-merge! h1 h2)
             (hash-table-ref h1 'k)))
(test 2 (let ((h1 (make-hash-table)) (h2 (make-hash-table)))
          (hash-table-set! h1 'a 1)
          (hash-table-set! h2 'b 2)
          (hash-table-size (hash-table-merge! h1 h2))))
;; self-merge must not corrupt (#278 regression)
(test 1 (let ((ht (make-hash-table)))
          (hash-table-set! ht 'k 'v)
          (hash-table-merge! ht ht)
          (hash-table-size ht)))
(test 'caught (guard (e (#t 'caught)) (hash-table-merge! (make-hash-table) '())))

;;; --- hash functions ---
(test #t (integer? (hash '(a b c))))
(test #t (= (hash "abc") (hash "abc")))
(test #t (= (hash (list 1 2)) (hash (list 1 2))))
(test #t (let ((h (hash 'sym 10))) (and (<= 0 h) (< h 10))))
(test #t (= (string-hash "abc") (string-hash (string-copy "abc"))))
(test #t (let ((h (string-hash "abc" 7))) (and (<= 0 h) (< h 7))))
(test #t (= (string-ci-hash "AbC") (string-ci-hash "abc")))
(test #t (= (string-ci-hash "ΛΆΜΔΑ") (string-ci-hash "λάμδα")))
(test #t (integer? (hash-by-identity 'x)))
(test #t (let ((h (hash-by-identity 'x 5))) (and (<= 0 h) (< h 5))))
(test 'caught (guard (e (#t 'caught)) (hash 'x 0)))
(test 'caught (guard (e (#t 'caught)) (hash 'x -3)))
(test 'caught (guard (e (#t 'caught)) (string-hash 42)))
(test 'caught (guard (e (#t 'caught)) (string-ci-hash 42)))
(test 'caught (guard (e (#t 'caught)) (string-hash "a" 0)))

;;; --- equivalence/hash accessors + custom functions ---
(test #t (procedure? (hash-table-equivalence-function (make-hash-table))))
(test #t (procedure? (hash-table-hash-function (make-hash-table))))
(test 'caught (guard (e (#t 'caught)) (hash-table-equivalence-function 42)))
;; make-hash-table and alist->hash-table accept but IGNORE custom
;; equivalence/hash procedures — an eq? table coalesces distinct equal
;; strings, and the accessor claims equal? regardless of what was passed.
;; FAIL: #1183 (custom equivalence/hash functions ignored; accessors lie)
;; (test 2 (let ((ht (make-hash-table eq?)))
;;           (hash-table-set! ht (string #\a) 'first)
;;           (hash-table-set! ht (string #\a) 'second)
;;           (hash-table-size ht)))
;; (test #t (eq? eq? (hash-table-equivalence-function (make-hash-table eq?))))

(test-end "primitives_hashtable audit")
