;; Audit tests for src/primitives_hashtable.zig — SRFI-69 hash tables.
;; Audit campaign Phase 2.11 (#1137).
;; Run directly and read the printed counts — run-all.sh only sees exit codes.

(import (scheme base) (scheme write) (srfi 69))
(import (scheme process-context) (srfi 64))

(test-begin "primitives_hashtable audit")

;;; --- constructors and predicate ---
(test-equal #t (hash-table? (make-hash-table)))
(test-equal #f (hash-table? '((a . 1))))
(test-equal #f (hash-table? #(1 2)))
(test-equal 0 (hash-table-size (make-hash-table)))

;;; --- set! / ref / ref/default ---
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht 'k 'v)
                 (hash-table-ref ht 'k)))
(test-equal 'new (let ((ht (make-hash-table)))
                   (hash-table-set! ht 'k 'old)
                   (hash-table-set! ht 'k 'new)     ; overwrite, size stays 1
                   (hash-table-ref ht 'k)))
(test-equal 1 (let ((ht (make-hash-table)))
                (hash-table-set! ht 'k 'old)
                (hash-table-set! ht 'k 'new)
                (hash-table-size ht)))
(test-equal 'from-thunk (hash-table-ref (make-hash-table) 'missing (lambda () 'from-thunk)))
(test-equal 'dflt (hash-table-ref/default (make-hash-table) 'missing 'dflt))
(test-equal 'caught (guard (e (#t 'caught)) (hash-table-ref (make-hash-table) 'missing)))
(test-equal 'caught (guard (e (#t 'caught))
                      (hash-table-ref (make-hash-table) 'missing (lambda () (error "boom")))))
(test-equal 'caught (guard (e (#t 'caught)) (hash-table-ref '((a . 1)) 'a)))
(test-equal 'caught (guard (e (#t 'caught)) (hash-table-set! "not-ht" 'k 'v)))

;;; --- key type coverage: hash/equality must agree for immediates,
;;;     strings, symbols, chars, and shallow structures ---
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht "key" 'v)
                 (hash-table-ref/default ht (string-copy "key") 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht #\x 'v)
                 (hash-table-ref/default ht #\x 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht 42 'v)
                 (hash-table-ref/default ht 42 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht 1.5 'v)
                 (hash-table-ref/default ht 1.5 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht #t 'v)
                 (hash-table-ref/default ht #t 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht '() 'v)
                 (hash-table-ref/default ht '() 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht (list 1 2) 'v)
                 (hash-table-ref/default ht (list 1 2) 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht (vector 1 "a") 'v)
                 (hash-table-ref/default ht (vector 1 "a") 'missing)))
(test-equal 'v (let ((ht (make-hash-table)))
                 (hash-table-set! ht (bytevector 1 2) 'v)
                 (hash-table-ref/default ht (bytevector 1 2) 'missing)))
;; Regression for #1180: heap-boxed numeric keys used to hash by pointer
;; while lookup compared by equal?, so entries became unfindable once the
;; table grew past one bucket-group.
(test-equal 0 (let ((ht (make-hash-table)))
                (do ((i 0 (+ i 1))) ((= i 30))
                  (hash-table-set! ht (+ (expt 2 100) i) i))
                (let ((mismatches 0))
                  (do ((i 0 (+ i 1))) ((= i 30))
                    (if (not (equal? i (hash-table-ref/default ht (+ (expt 2 100) i) 'missing)))
                        (set! mismatches (+ mismatches 1))))
                  mismatches)))
(test-equal 0 (let ((ht (make-hash-table)))
                (do ((i 0 (+ i 1))) ((= i 30))
                  (hash-table-set! ht (/ 1 (+ i 3)) i))
                (let ((mismatches 0))
                  (do ((i 0 (+ i 1))) ((= i 30))
                    (if (not (equal? i (hash-table-ref/default ht (/ 1 (+ i 3)) 'missing)))
                        (set! mismatches (+ mismatches 1))))
                  mismatches)))

;;; --- growth: many entries stay findable (fixnum/string/symbol keys) ---
(test-equal 0 (let ((ht (make-hash-table)))
                (do ((i 0 (+ i 1))) ((= i 100))
                  (hash-table-set! ht i (* i i)))
                (let ((misses 0))
                  (do ((i 0 (+ i 1))) ((= i 100))
                    (if (not (equal? (* i i) (hash-table-ref/default ht i 'missing)))
                        (set! misses (+ misses 1))))
                  misses)))
(test-equal 100 (let ((ht (make-hash-table)))
                  (do ((i 0 (+ i 1))) ((= i 100))
                    (hash-table-set! ht i i))
                  (hash-table-size ht)))

;;; --- exists? / delete! ---
(test-equal #t (let ((ht (make-hash-table)))
                 (hash-table-set! ht 'k 'v)
                 (hash-table-exists? ht 'k)))
(test-equal #f (hash-table-exists? (make-hash-table) 'k))
(test-equal '(#f 0) (let ((ht (make-hash-table)))
                      (hash-table-set! ht 'k 'v)
                      (hash-table-delete! ht 'k)
                      (list (hash-table-exists? ht 'k) (hash-table-size ht))))
;; deleting a missing key is a no-op
(test-equal 1 (let ((ht (make-hash-table)))
                (hash-table-set! ht 'k 'v)
                (hash-table-delete! ht 'other)
                (hash-table-size ht)))
;; delete then re-insert (tombstone reuse)
(test-equal 'v2 (let ((ht (make-hash-table)))
                  (hash-table-set! ht 'k 'v1)
                  (hash-table-delete! ht 'k)
                  (hash-table-set! ht 'k 'v2)
                  (hash-table-ref ht 'k)))

;;; --- keys / values / ->alist ---
(test-equal '(a b) (let ((ht (make-hash-table)))
                     (hash-table-set! ht 'a 1)
                     (hash-table-set! ht 'b 2)
                     (let ((ks (hash-table-keys ht)))
                       (if (memq 'a ks) (if (memq 'b ks) (list 'a 'b) 'missing-b) 'missing-a))))
(test-equal 3 (let ((ht (make-hash-table)))
                (hash-table-set! ht 'a 1)
                (hash-table-set! ht 'b 2)
                (let loop ((vs (hash-table-values ht)) (sum 0))
                  (if (null? vs) sum (loop (cdr vs) (+ sum (car vs)))))))
(test-equal '((k . v)) (let ((ht (make-hash-table)))
                         (hash-table-set! ht 'k 'v)
                         (hash-table->alist ht)))
(test-equal '() (hash-table->alist (make-hash-table)))

;;; --- alist->hash-table ---
(test-equal 2 (hash-table-size (alist->hash-table '((a . 1) (b . 2)))))
;; SRFI-69: earlier associations take precedence
(test-equal 1 (hash-table-ref (alist->hash-table '((k . 1) (k . 2))) 'k))
(test-equal 0 (hash-table-size (alist->hash-table '())))
;; 12 entries (non-power-of-two count) all retrievable
(test-equal '(12 12 1)
    (let ((ht (alist->hash-table '((a . 1) (b . 2) (c . 3) (d . 4) (e . 5) (f . 6)
                                  (g . 7) (h . 8) (i . 9) (j . 10) (k . 11) (l . 12)))))
      (list (hash-table-size ht)
            (hash-table-ref/default ht 'l 'missing)
            (hash-table-ref/default ht 'a 'missing))))
(test-equal 'caught (guard (e (#t 'caught)) (alist->hash-table '(not-a-pair))))
(test-equal 'caught (guard (e (#t 'caught)) (alist->hash-table 42)))

;;; --- walk / fold ---
(test-equal 6 (let ((ht (make-hash-table)) (sum 0))
                (hash-table-set! ht 'a 1)
                (hash-table-set! ht 'b 2)
                (hash-table-set! ht 'c 3)
                (hash-table-walk ht (lambda (k v) (set! sum (+ sum v))))
                sum))
(test-equal 6 (let ((ht (make-hash-table)))
                (hash-table-set! ht 'a 1)
                (hash-table-set! ht 'b 2)
                (hash-table-set! ht 'c 3)
                (hash-table-fold ht (lambda (k v acc) (+ acc v)) 0)))
(test-equal 0 (hash-table-fold (make-hash-table) (lambda (k v acc) (+ acc 1)) 0))
(test-equal 'caught (guard (e (#t 'caught))
                      (let ((ht (make-hash-table)))
                        (hash-table-set! ht 'k 'v)
                        (hash-table-walk ht (lambda (k v) (error "boom"))))))
(test-equal 'caught (guard (e (#t 'caught))
                      (let ((ht (make-hash-table)))
                        (hash-table-set! ht 'k 'v)
                        (hash-table-fold ht (lambda (k v acc) (error "boom")) 0))))
;; mutation during walk: inserting during iteration must not crash;
;; all original entries are still visited (snapshot semantics)
(test-equal 3 (let ((ht (make-hash-table)) (seen 0))
                (hash-table-set! ht 'a 1)
                (hash-table-set! ht 'b 2)
                (hash-table-set! ht 'c 3)
                (hash-table-walk ht (lambda (k v)
                                      (hash-table-set! ht (list k) v)
                                      (set! seen (+ seen 1))))
                seen))
;; Regression test for #1181: walk/fold snapshot keys/values must be rooted
;; so GC doesn't free them when the callback deletes entries and allocates.
(test-equal '(435 0)
    (let ((ht (make-hash-table)) (sum 0) (bad 0))
      (do ((i 0 (+ i 1))) ((= i 30))
        (hash-table-set! ht (cons i 'key) (cons i 'val)))
      (hash-table-walk ht
        (lambda (k v)
          (do ((j 0 (+ j 1))) ((= j 30))
            (hash-table-delete! ht (cons j 'key)))
          (do ((j 0 (+ j 1))) ((= j 100))
            (cons j (make-vector 4 j)))
          (if (and (pair? k) (pair? v) (eq? (cdr k) 'key) (eq? (cdr v) 'val)
                   (= (car k) (car v)))
              (set! sum (+ sum (car k)))
              (set! bad (+ bad 1)))))
      (list sum bad)))

;;; --- update!/default ---
(test-equal 11 (let ((ht (make-hash-table)))
                 (hash-table-set! ht 'k 10)
                 (hash-table-update!/default ht 'k (lambda (x) (+ x 1)) 0)
                 (hash-table-ref ht 'k)))
(test-equal 1 (let ((ht (make-hash-table)))
                (hash-table-update!/default ht 'k (lambda (x) (+ x 1)) 0)
                (hash-table-ref ht 'k)))
(test-equal 'caught (guard (e (#t 'caught))
                      (hash-table-update!/default (make-hash-table) 'k
                                                  (lambda (x) (error "boom")) 0)))
(test-equal 11 (let ((ht (make-hash-table)))
                 (hash-table-set! ht 'k 10)
                 (hash-table-update! ht 'k (lambda (x) (+ x 1)))
                 (hash-table-ref ht 'k)))

;;; --- copy / merge! ---
(test-equal '(1 2) (let ((h1 (make-hash-table)))
                     (hash-table-set! h1 'k 1)
                     (let ((h2 (hash-table-copy h1)))
                       (hash-table-set! h2 'k 2)
                       (list (hash-table-ref h1 'k) (hash-table-ref h2 'k)))))
(test-equal 'new (let ((h1 (make-hash-table)) (h2 (make-hash-table)))
                   (hash-table-set! h1 'k 'old)
                   (hash-table-set! h2 'k 'new)
                   (hash-table-merge! h1 h2)
                   (hash-table-ref h1 'k)))
(test-equal 2 (let ((h1 (make-hash-table)) (h2 (make-hash-table)))
                (hash-table-set! h1 'a 1)
                (hash-table-set! h2 'b 2)
                (hash-table-size (hash-table-merge! h1 h2))))
;; self-merge must not corrupt (#278 regression)
(test-equal 1 (let ((ht (make-hash-table)))
                (hash-table-set! ht 'k 'v)
                (hash-table-merge! ht ht)
                (hash-table-size ht)))
(test-equal 'caught (guard (e (#t 'caught)) (hash-table-merge! (make-hash-table) '())))

;;; --- hash functions ---
(test-equal #t (integer? (hash '(a b c))))
(test-equal #t (= (hash "abc") (hash "abc")))
(test-equal #t (= (hash (list 1 2)) (hash (list 1 2))))
(test-equal #t (let ((h (hash 'sym 10))) (and (<= 0 h) (< h 10))))
(test-equal #t (= (string-hash "abc") (string-hash (string-copy "abc"))))
(test-equal #t (let ((h (string-hash "abc" 7))) (and (<= 0 h) (< h 7))))
(test-equal #t (= (string-ci-hash "AbC") (string-ci-hash "abc")))
(test-equal #t (= (string-ci-hash "ΛΆΜΔΑ") (string-ci-hash "λάμδα")))
(test-equal #t (integer? (hash-by-identity 'x)))
(test-equal #t (let ((h (hash-by-identity 'x 5))) (and (<= 0 h) (< h 5))))
(test-equal 'caught (guard (e (#t 'caught)) (hash 'x 0)))
(test-equal 'caught (guard (e (#t 'caught)) (hash 'x -3)))
(test-equal 'caught (guard (e (#t 'caught)) (string-hash 42)))
(test-equal 'caught (guard (e (#t 'caught)) (string-ci-hash 42)))
(test-equal 'caught (guard (e (#t 'caught)) (string-hash "a" 0)))

;;; --- equivalence/hash accessors + custom functions ---
(test-equal #t (procedure? (hash-table-equivalence-function (make-hash-table))))
(test-equal #t (procedure? (hash-table-hash-function (make-hash-table))))
(test-equal 'caught (guard (e (#t 'caught)) (hash-table-equivalence-function 42)))
;; #1183: custom equivalence/hash functions now honored
(test-equal 2 (let ((ht (make-hash-table eq?)))
                (hash-table-set! ht (string #\a) 'first)
                (hash-table-set! ht (string #\a) 'second)
                (hash-table-size ht)))
(test-equal #t (eq? eq? (hash-table-equivalence-function (make-hash-table eq?))))

(let ((runner (test-runner-current)))
  (test-end "primitives_hashtable audit")
  (when (> (test-runner-fail-count runner) 0) (exit 1)))
