#!/usr/bin/env python3
"""Generate the Unicode range tables embedded in the portable SRFI libraries.

Two libraries need Unicode general categories that R7RS `(scheme char)` does
not expose, and both are portable R7RS, so the data has to live in the library
itself rather than behind a Kaappi primitive:

  --target 115  (default)  Titlecase (Lt) and Symbol (S*) categories plus the
                           UAX #29 grapheme cluster break classes, as flat
                           vectors searched by `%in-table?`.
  --target 14              Titlecase (Lt), Symbol (S*) and Punctuation (P*)
                           categories, as `((lo . hi) ...)` range lists in the
                           inversion-list representation `(srfi 14)` uses.

Run this after a Unicode version bump and paste the output over the
";;; Unicode tables" block in the corresponding .sld.  Keep UNICODE_VERSION in
step with tools/gen_unicode_tables.py so the class names agree with
char-alphabetic? and friends.
"""

import argparse
import os
import sys
import urllib.request

UNICODE_VERSION = "15.1.0"
BASE = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/"
UNICODE_DATA_URL = BASE + "UnicodeData.txt"
GRAPHEME_BREAK_URL = BASE + "auxiliary/GraphemeBreakProperty.txt"


def download(url, path):
    if os.path.exists(path):
        return
    # stderr: stdout is the Scheme source, meant to be redirected to a file.
    print(f"Downloading {url}...", file=sys.stderr)
    urllib.request.urlretrieve(url, path)


def parse_categories(path):
    """UnicodeData.txt -> {general category: set of codepoints}.

    Ranges are written as a "<..., First>"/"<..., Last>" pair of lines.
    """
    cats = {}
    first = None
    with open(path) as f:
        for line in f:
            fields = line.split(";")
            if len(fields) < 3:
                continue
            cp = int(fields[0], 16)
            name = fields[1]
            cat = fields[2]
            if name.endswith(", First>"):
                first = cp
                continue
            if name.endswith(", Last>"):
                cats.setdefault(cat, set()).update(range(first, cp + 1))
                first = None
                continue
            cats.setdefault(cat, set()).add(cp)
    return cats


def parse_grapheme_break(path):
    """GraphemeBreakProperty.txt -> {break class: set of codepoints}."""
    classes = {}
    with open(path) as f:
        for line in f:
            line = line.split("#")[0].strip()
            if not line:
                continue
            cps, name = (f.strip() for f in line.split(";"))
            if ".." in cps:
                lo, hi = (int(x, 16) for x in cps.split(".."))
            else:
                lo = hi = int(cps, 16)
            classes.setdefault(name, set()).update(range(lo, hi + 1))
    return classes


def to_ranges(cps):
    ranges = []
    for cp in sorted(cps):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


def emit(name, cps, comment):
    """One Scheme definition: a flat vector of inclusive [lo hi] pairs."""
    ranges = to_ranges(cps)
    nums = [str(n) for r in ranges for n in r]
    lines = [f"    ;; {comment} ({len(ranges)} ranges)", f"    (define {name}"]
    line = "      '#("
    for n in nums:
        if len(line) + len(n) + 1 > 78:
            lines.append(line.rstrip())
            line = "         "
        line += n + " "
    lines.append(line.rstrip() + "))")
    return "\n".join(lines)


def emit_pairs(name, cps, comment):
    """One Scheme definition: a list of inclusive (lo . hi) codepoint pairs."""
    ranges = to_ranges(cps)
    lines = [f"    ;; {comment} ({len(ranges)} ranges)", f"    (define {name}"]
    line = "      '("
    for lo, hi in ranges:
        pair = f"({lo} . {hi})"
        if len(line) + len(pair) + 1 > 78:
            lines.append(line.rstrip())
            line = "        "
        line += pair + " "
    lines.append(line.rstrip() + "))")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target", choices=("115", "14"), default="115")
    args = ap.parse_args()

    cache = os.path.join(os.path.dirname(__file__), ".cache")
    os.makedirs(cache, exist_ok=True)
    udata = os.path.join(cache, "UnicodeData.txt")
    download(UNICODE_DATA_URL, udata)
    cats = parse_categories(udata)
    symbol = set().union(*(cats[c] for c in ("Sm", "Sc", "Sk", "So")))

    header = [
        f";;; Unicode tables -- generated by tools/gen_srfi_charsets.py"
        f" --target {args.target}",
        f";;; from UCD {UNICODE_VERSION}.  Do not edit by hand.",
        ";;;",
    ]

    if args.target == "14":
        punctuation = set().union(
            *(cats[c] for c in ("Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po"))
        )
        letter = set().union(*(cats[c] for c in ("Lu", "Ll", "Lt", "Lm", "Lo")))
        separator = set().union(*(cats[c] for c in ("Zs", "Zl", "Zp")))
        out = header + [
            ";;; Each table is a list of inclusive (lo . hi) codepoint pairs in",
            ";;; ascending order -- the same inversion-list shape a char-set's",
            ";;; own ranges field holds, so these drop straight in.",
            ";;;",
            ";;; SRFI 14 defines its standard sets by Unicode general category,",
            ";;; so every one of them comes from here rather than from a scan",
            ";;; over (scheme char)'s predicates.  See the library header.",
            "",
            emit_pairs("%tbl-letter", letter, "general categories Lu, Ll, Lt, Lm, Lo"),
            "",
            emit_pairs("%tbl-lower-case", cats["Ll"], "general category Ll"),
            "",
            emit_pairs("%tbl-upper-case", cats["Lu"], "general category Lu"),
            "",
            emit_pairs("%tbl-title-case", cats["Lt"], "general category Lt"),
            "",
            emit_pairs("%tbl-digit", cats["Nd"], "general category Nd"),
            "",
            # "the space/line/paragraph separator categories (Zs, Zl, Zp) plus
            # ... U+0009 through U+000D, and U+0020" -- SRFI 14, char-set:whitespace
            emit_pairs(
                "%tbl-whitespace",
                separator | set(range(0x09, 0x0E)),
                "general categories Zs, Zl, Zp plus U+0009..U+000D",
            ),
            "",
            # "Blank chars are horizontal whitespace" -- Zs plus tab.
            emit_pairs(
                "%tbl-blank", cats["Zs"] | {0x09}, "general category Zs plus U+0009"
            ),
            "",
            emit_pairs(
                "%tbl-punctuation",
                punctuation,
                "general categories Pc, Pd, Ps, Pe, Pi, Pf, Po",
            ),
            "",
            emit_pairs(
                "%tbl-symbol", symbol, "general categories Sm, Sc, Sk, So"
            ),
        ]
        print("\n".join(out))
        return

    gbreak = os.path.join(cache, "GraphemeBreakProperty.txt")
    download(GRAPHEME_BREAK_URL, gbreak)
    gcb = parse_grapheme_break(gbreak)

    # Extend, SpacingMark and ZWJ all join to the left (UAX #29 GB9/GB9a), so
    # the matcher only ever asks "is this a mark?" -- one table serves all three.
    mark = gcb["Extend"] | gcb["SpacingMark"] | gcb["ZWJ"]

    out = header + [
        ";;; Each table is a flat vector of inclusive [lo hi] codepoint pairs in",
        ";;; ascending order, searched by %in-table?.",
        "",
        emit("%cs-title-case", cats["Lt"], "general category Lt"),
        "",
        emit("%cs-symbol", symbol, "general categories Sm, Sc, Sk, So"),
        "",
        emit("%cs-mark", mark, "UAX #29 Extend + SpacingMark + ZWJ"),
        "",
        emit("%cs-gcb-control", gcb["Control"], "UAX #29 Control"),
        "",
        emit("%cs-prepend", gcb["Prepend"], "UAX #29 Prepend"),
    ]
    print("\n".join(out))


if __name__ == "__main__":
    main()
