#!/usr/bin/env python3
"""Generate Zig Unicode case mapping and property tables from UnicodeData.txt,
CaseFolding.txt, and DerivedCoreProperties.txt."""

import urllib.request
import os

UNICODE_DATA_URL = "https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt"
CASE_FOLDING_URL = "https://www.unicode.org/Public/15.1.0/ucd/CaseFolding.txt"
DERIVED_PROPS_URL = "https://www.unicode.org/Public/15.1.0/ucd/DerivedCoreProperties.txt"

def download(url, path):
    if os.path.exists(path):
        return
    print(f"Downloading {url}...")
    urllib.request.urlretrieve(url, path)

def parse_unicode_data(path):
    uppercase_letters = set()
    lowercase_letters = set()
    upcase_map = {}    # lowercase cp -> uppercase cp
    downcase_map = {}  # uppercase cp -> lowercase cp

    with open(path) as f:
        for line in f:
            fields = line.strip().split(';')
            if len(fields) < 15:
                continue
            cp = int(fields[0], 16)
            category = fields[2]
            simple_upper = fields[12].strip()
            simple_lower = fields[13].strip()

            if category == 'Lu':
                uppercase_letters.add(cp)
            elif category == 'Ll':
                lowercase_letters.add(cp)

            if simple_upper:
                upcase_map[cp] = int(simple_upper, 16)
            if simple_lower:
                downcase_map[cp] = int(simple_lower, 16)

    return uppercase_letters, lowercase_letters, upcase_map, downcase_map

def parse_case_folding(path):
    fold_map = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            fields = line.split(';')
            if len(fields) < 3:
                continue
            status = fields[1].strip()
            if status not in ('C', 'S'):
                continue
            cp = int(fields[0].strip(), 16)
            folded = int(fields[2].strip().split()[0], 16)
            fold_map[cp] = folded
    return fold_map

def parse_derived_core_properties(path):
    """Parse DerivedCoreProperties.txt for Uppercase, Lowercase, Alphabetic ranges."""
    props = {"Uppercase": [], "Lowercase": [], "Alphabetic": [], "Cased": []}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            fields = line.split(';')
            if len(fields) < 2:
                continue
            prop = fields[1].split('#')[0].strip()
            if prop not in props:
                continue
            cp_field = fields[0].strip()
            if '..' in cp_field:
                lo, hi = cp_field.split('..')
                props[prop].append((int(lo, 16), int(hi, 16)))
            else:
                cp = int(cp_field, 16)
                props[prop].append((cp, cp))

    # Sort and merge adjacent/overlapping ranges
    for prop in props:
        ranges = sorted(props[prop])
        merged = []
        for lo, hi in ranges:
            if merged and lo <= merged[-1][1] + 1:
                merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
            else:
                merged.append((lo, hi))
        props[prop] = merged

    return props


def fmt(cp):
    return f"0x{cp:04X}"

def write_table(lines, name, entries, key_name, val_name):
    lines.append(f"pub const {name} = [_]CaseEntry{{")
    for key, val in entries:
        lines.append(f"    .{{ .from = {fmt(key)}, .to = {fmt(val)} }},")
    lines.append("};")
    lines.append(f"// {len(entries)} entries")
    lines.append("")

def write_search_fn(lines, fn_name, table_name):
    lines.append(f"pub fn {fn_name}(cp: u21) ?u21 {{")
    lines.append(f"    var lo: usize = 0;")
    lines.append(f"    var hi: usize = {table_name}.len;")
    lines.append(f"    while (lo < hi) {{")
    lines.append(f"        const mid = lo + (hi - lo) / 2;")
    lines.append(f"        if ({table_name}[mid].from == cp) return {table_name}[mid].to;")
    lines.append(f"        if ({table_name}[mid].from < cp) {{ lo = mid + 1; }} else {{ hi = mid; }}")
    lines.append(f"    }}")
    lines.append(f"    return null;")
    lines.append(f"}}")
    lines.append("")

def write_range_table(lines, name, ranges):
    lines.append(f"pub const {name} = [_]Range{{")
    for lo, hi in ranges:
        lines.append(f"    .{{ .lo = {fmt(lo)}, .hi = {fmt(hi)} }},")
    lines.append("};")
    lines.append(f"// {len(ranges)} ranges")
    lines.append("")

def generate_zig(uppercase_letters, lowercase_letters, upcase_map, downcase_map, fold_map, derived_props):
    lines = []
    lines.append("// Auto-generated from Unicode 15.1 UnicodeData.txt, CaseFolding.txt,")
    lines.append("// and DerivedCoreProperties.txt")
    lines.append("// Generated by tools/gen_unicode_tables.py — do not edit by hand")
    lines.append("")

    lines.append("pub const CaseEntry = struct { from: u21, to: u21 };")
    lines.append("pub const Range = struct { lo: u21, hi: u21 };")
    lines.append("")

    # Upcase table: sorted by 'from' (lowercase codepoint)
    upcase_sorted = sorted(upcase_map.items())
    write_table(lines, "upcase_table", upcase_sorted, "from", "to")
    write_search_fn(lines, "findUpper", "upcase_table")

    # Downcase table: sorted by 'from' (uppercase codepoint)
    downcase_sorted = sorted(downcase_map.items())
    write_table(lines, "downcase_table", downcase_sorted, "from", "to")
    write_search_fn(lines, "findLower", "downcase_table")

    # Case folding: only entries that differ from simple downcase
    fold_extra = {}
    for cp, folded in sorted(fold_map.items()):
        if cp <= 0x7F:
            continue
        if cp in downcase_map and downcase_map[cp] == folded:
            continue
        fold_extra[cp] = folded

    fold_sorted = sorted(fold_extra.items())
    write_table(lines, "fold_table", fold_sorted, "from", "to")
    write_search_fn(lines, "findFold", "fold_table")

    # Unicode derived property range tables (from DerivedCoreProperties.txt)
    write_range_table(lines, "uppercase_ranges", derived_props["Uppercase"])
    write_range_table(lines, "lowercase_ranges", derived_props["Lowercase"])
    write_range_table(lines, "alphabetic_ranges", derived_props["Alphabetic"])
    write_range_table(lines, "cased_ranges", derived_props["Cased"])

    # Binary search for range tables
    lines.append("pub fn inRanges(comptime table: []const Range, cp: u21) bool {")
    lines.append("    var lo: usize = 0;")
    lines.append("    var hi: usize = table.len;")
    lines.append("    while (lo < hi) {")
    lines.append("        const mid = lo + (hi - lo) / 2;")
    lines.append("        if (cp < table[mid].lo) {")
    lines.append("            hi = mid;")
    lines.append("        } else if (cp > table[mid].hi) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else {")
    lines.append("            return true;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return false;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"

def main():
    cache_dir = os.path.join(os.path.dirname(__file__), ".cache")
    os.makedirs(cache_dir, exist_ok=True)

    udata_path = os.path.join(cache_dir, "UnicodeData.txt")
    cfold_path = os.path.join(cache_dir, "CaseFolding.txt")
    dprops_path = os.path.join(cache_dir, "DerivedCoreProperties.txt")

    download(UNICODE_DATA_URL, udata_path)
    download(CASE_FOLDING_URL, cfold_path)
    download(DERIVED_PROPS_URL, dprops_path)

    print("Parsing UnicodeData.txt...")
    upper_set, lower_set, upcase_map, downcase_map = parse_unicode_data(udata_path)
    print(f"  Lu: {len(upper_set)}, Ll: {len(lower_set)}")
    print(f"  Upcase mappings: {len(upcase_map)}, Downcase mappings: {len(downcase_map)}")

    print("Parsing CaseFolding.txt...")
    fold_map = parse_case_folding(cfold_path)
    print(f"  Case folding (C+S): {len(fold_map)}")

    print("Parsing DerivedCoreProperties.txt...")
    derived_props = parse_derived_core_properties(dprops_path)
    for prop in ("Uppercase", "Lowercase", "Alphabetic", "Cased"):
        total = sum(hi - lo + 1 for lo, hi in derived_props[prop])
        print(f"  {prop}: {len(derived_props[prop])} ranges ({total} codepoints)")

    zig_src = generate_zig(upper_set, lower_set, upcase_map, downcase_map, fold_map, derived_props)

    out_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "src", "unicode_tables.zig")
    with open(out_path, 'w') as f:
        f.write(zig_src)

    print(f"Written {out_path} ({zig_src.count(chr(10))} lines)")
    print(f"  upcase_table: {len(upcase_map)} entries")
    print(f"  downcase_table: {len(downcase_map)} entries")

    # Verify no duplicates
    upcase_keys = [k for k, _ in sorted(upcase_map.items())]
    downcase_keys = [k for k, _ in sorted(downcase_map.items())]
    assert len(upcase_keys) == len(set(upcase_keys)), "duplicate keys in upcase_table!"
    assert len(downcase_keys) == len(set(downcase_keys)), "duplicate keys in downcase_table!"
    print("  No duplicate keys ✓")

if __name__ == "__main__":
    main()
