const std = @import("std");
const types = @import("types.zig");
const ir_mod = @import("ir.zig");
const memory = @import("memory.zig");
const compiler_mod = @import("compiler.zig");
const reader_mod = @import("reader.zig");

const Value = types.Value;
const Node = ir_mod.Node;

pub const CCodegenError = error{
    OutOfMemory,
    UnsupportedForm,
};

pub const CCodegen = struct {
    allocator: std.mem.Allocator,
    output: std.ArrayList(u8),
    temp_counter: u32 = 0,

    pub fn init(allocator: std.mem.Allocator) CCodegen {
        return .{
            .allocator = allocator,
            .output = .empty,
        };
    }

    pub fn deinit(self: *CCodegen) void {
        self.output.deinit(self.allocator);
    }

    fn nextTemp(self: *CCodegen) u32 {
        const t = self.temp_counter;
        self.temp_counter += 1;
        return t;
    }

    fn write(self: *CCodegen, s: []const u8) CCodegenError!void {
        self.output.appendSlice(self.allocator, s) catch return CCodegenError.OutOfMemory;
    }

    fn writeFmt(self: *CCodegen, comptime fmt: []const u8, args: anytype) CCodegenError!void {
        var buf: [512]u8 = undefined;
        const slice = std.fmt.bufPrint(&buf, fmt, args) catch return CCodegenError.OutOfMemory;
        self.output.appendSlice(self.allocator, slice) catch return CCodegenError.OutOfMemory;
    }

    pub fn generate(self: *CCodegen, node: *Node) CCodegenError![]const u8 {
        try self.write(
            \\/* Generated by Kaappi IR → C codegen */
            \\#include <stdint.h>
            \\#include <stdio.h>
            \\
            \\typedef uint64_t Value;
            \\
            \\/* NaN-boxed value constructors matching types.zig */
            \\static inline Value make_fixnum(int64_t n) {
            \\    return 0xFFFD000000000000ULL | ((uint64_t)n & 0xFFFFFFFFFFFFULL);
            \\}
            \\static inline int64_t to_fixnum(Value v) {
            \\    int64_t raw = (int64_t)(v & 0xFFFFFFFFFFFFULL);
            \\    if (raw & 0x800000000000ULL) raw |= (int64_t)0xFFFF000000000000ULL;
            \\    return raw;
            \\}
            \\static inline int is_fixnum(Value v) { return (v >> 48) == 0xFFFD; }
            \\#define KAAPPI_TRUE  0xFFFE000000000002ULL
            \\#define KAAPPI_FALSE 0xFFFE000000000006ULL
            \\#define KAAPPI_NIL   0xFFFE000000000000ULL
            \\#define KAAPPI_VOID  0xFFFE00000000000AULL
            \\
            \\Value kaappi_main(void) {
            \\
        );

        const result = try self.emitExpr(node);
        try self.writeFmt("    return t{d};\n", .{result});
        try self.write("}\n\nint main(void) {\n    Value result = kaappi_main();\n    if (is_fixnum(result)) printf(\"%lld\\n\", (long long)to_fixnum(result));\n    else if (result == KAAPPI_TRUE) printf(\"#t\\n\");\n    else if (result == KAAPPI_FALSE) printf(\"#f\\n\");\n    else printf(\"<value>\\n\");\n    return 0;\n}\n");

        return self.output.toOwnedSlice(self.allocator);
    }

    fn emitExpr(self: *CCodegen, node: *Node) CCodegenError!u32 {
        switch (node.tag) {
            .constant => {
                const t = self.nextTemp();
                const val = node.data.constant;
                if (types.isFixnum(val)) {
                    try self.writeFmt("    Value t{d} = make_fixnum({d}LL);\n", .{ t, types.toFixnum(val) });
                } else if (val == types.TRUE) {
                    try self.writeFmt("    Value t{d} = KAAPPI_TRUE;\n", .{t});
                } else if (val == types.FALSE) {
                    try self.writeFmt("    Value t{d} = KAAPPI_FALSE;\n", .{t});
                } else if (val == types.NIL) {
                    try self.writeFmt("    Value t{d} = KAAPPI_NIL;\n", .{t});
                } else if (val == types.VOID) {
                    try self.writeFmt("    Value t{d} = KAAPPI_VOID;\n", .{t});
                } else {
                    try self.writeFmt("    Value t{d} = 0x{x}ULL; /* unknown constant */\n", .{ t, val });
                }
                return t;
            },
            .@"if" => {
                const data = node.data.@"if";
                const test_t = try self.emitExpr(data.test_expr);
                const result_t = self.nextTemp();
                try self.writeFmt("    Value t{d};\n", .{result_t});
                try self.writeFmt("    if (t{d} != KAAPPI_FALSE) {{\n", .{test_t});
                const cons_t = try self.emitExpr(data.consequent);
                try self.writeFmt("        t{d} = t{d};\n", .{ result_t, cons_t });
                if (data.alternate) |alt| {
                    try self.write("    } else {\n");
                    const alt_t = try self.emitExpr(alt);
                    try self.writeFmt("        t{d} = t{d};\n", .{ result_t, alt_t });
                } else {
                    try self.write("    } else {\n");
                    try self.writeFmt("        t{d} = KAAPPI_VOID;\n", .{result_t});
                }
                try self.write("    }\n");
                return result_t;
            },
            .begin => {
                var last_t: u32 = 0;
                for (node.data.begin) |expr| {
                    last_t = try self.emitExpr(@constCast(expr));
                }
                if (node.data.begin.len == 0) {
                    last_t = self.nextTemp();
                    try self.writeFmt("    Value t{d} = KAAPPI_VOID;\n", .{last_t});
                }
                return last_t;
            },
            else => {
                const t = self.nextTemp();
                try self.writeFmt("    Value t{d} = KAAPPI_VOID; /* unsupported: {s} */\n", .{ t, @tagName(node.tag) });
                return t;
            },
        }
    }
};

test "C codegen: integer literal" {
    var gc = memory.GC.init(std.testing.allocator);
    defer gc.deinit();
    var ir = ir_mod.IR.init(std.testing.allocator);
    defer ir.deinit();

    const node = try ir.makeConst(types.makeFixnum(42));
    var codegen = CCodegen.init(std.testing.allocator);
    defer codegen.deinit();
    const c_code = try codegen.generate(node);
    defer std.testing.allocator.free(c_code);
    try std.testing.expect(std.mem.indexOf(u8, c_code, "make_fixnum(42LL)") != null);
}

test "C codegen: if expression" {
    var gc = memory.GC.init(std.testing.allocator);
    defer gc.deinit();
    var ir = ir_mod.IR.init(std.testing.allocator);
    defer ir.deinit();

    const test_node = try ir.makeConst(types.TRUE);
    const cons = try ir.makeConst(types.makeFixnum(1));
    const alt = try ir.makeConst(types.makeFixnum(2));
    const if_node = try ir.makeIf(test_node, cons, alt);

    var codegen = CCodegen.init(std.testing.allocator);
    defer codegen.deinit();
    const c_code = try codegen.generate(if_node);
    defer std.testing.allocator.free(c_code);
    try std.testing.expect(std.mem.indexOf(u8, c_code, "KAAPPI_FALSE") != null);
    try std.testing.expect(std.mem.indexOf(u8, c_code, "make_fixnum(1LL)") != null);
    try std.testing.expect(std.mem.indexOf(u8, c_code, "make_fixnum(2LL)") != null);
}
