const std = @import("std");
const ir = @import("ir.zig");
const types = @import("types.zig");

const Value = types.Value;

pub const LLVMEmitter = struct {
    buf: std.ArrayList(u8),
    symbols: std.StringHashMap(void),
    tmp_counter: u32,
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) LLVMEmitter {
        return .{
            .buf = .empty,
            .symbols = std.StringHashMap(void).init(allocator),
            .tmp_counter = 0,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *LLVMEmitter) void {
        self.buf.deinit(self.allocator);
        self.symbols.deinit();
    }

    pub fn emitProgram(self: *LLVMEmitter, nodes: []const *ir.Node) EmitError!void {
        try self.emitPreamble();

        var sym_buf: [64][]const u8 = undefined;
        var sym_count: usize = 0;
        self.collectSymbols(nodes, &sym_buf, &sym_count);
        try self.emitSymbolConstants(sym_buf[0..sym_count]);

        try self.write("\ndefine i32 @main() {\nentry:\n");
        try self.write("  %vm = call ptr @kaappi_runtime_init()\n");

        for (nodes) |node| {
            _ = try self.emitNode(node);
        }

        try self.write("\n  call void @kaappi_runtime_deinit(ptr %vm)\n");
        try self.write("  ret i32 0\n}\n");
    }

    fn emitNode(self: *LLVMEmitter, node: *const ir.Node) EmitError![]const u8 {
        return switch (node.tag) {
            .constant => try self.emitConstant(node.data.constant),
            .global_ref => try self.emitGlobalRef(node.data.global_ref),
            .call => try self.emitCall(node.data.call),
            .begin => try self.emitBegin(node.data.begin),
            else => error.UnsupportedNodeType,
        };
    }

    fn emitConstant(self: *LLVMEmitter, value: Value) EmitError![]const u8 {
        const tmp = try self.freshTemp();
        const signed: i64 = @bitCast(value);
        try self.print("  {s} = add i64 0, {d}\n", .{ tmp, signed });
        return tmp;
    }

    fn emitGlobalRef(self: *LLVMEmitter, sym: Value) EmitError![]const u8 {
        if (!types.isSymbol(sym)) return error.UnsupportedNodeType;
        const name = types.symbolName(sym);
        const tmp = try self.freshTemp();
        try self.print("  {s} = call i64 @kaappi_global_lookup(ptr %vm, ptr @.sym.{s}, i64 {d})\n", .{ tmp, name, name.len });
        return tmp;
    }

    fn emitCall(self: *LLVMEmitter, call: ir.CallData) EmitError![]const u8 {
        const callee = try self.emitNode(call.operator);
        const nargs = call.args.len;

        var arg_tmps: [256][]const u8 = undefined;
        for (call.args, 0..) |arg, i| {
            arg_tmps[i] = try self.emitNode(arg);
        }

        const result = try self.freshTemp();

        if (nargs == 0) {
            try self.print("  {s} = call i64 @kaappi_call_scheme(ptr %vm, i64 {s}, ptr null, i64 0)\n", .{ result, callee });
        } else {
            const args_alloca = try self.freshTemp();
            try self.print("  {s} = alloca [{d} x i64], align 8\n", .{ args_alloca, nargs });

            for (0..nargs) |i| {
                const gep = try self.freshTemp();
                try self.print("  {s} = getelementptr [1 x i64], ptr {s}, i64 {d}\n", .{ gep, args_alloca, i });
                try self.print("  store i64 {s}, ptr {s}\n", .{ arg_tmps[i], gep });
            }

            try self.print("  {s} = call i64 @kaappi_call_scheme(ptr %vm, i64 {s}, ptr {s}, i64 {d})\n", .{ result, callee, args_alloca, nargs });
        }

        return result;
    }

    fn emitBegin(self: *LLVMEmitter, exprs: []const *ir.Node) EmitError![]const u8 {
        var last: []const u8 = "";
        for (exprs) |expr| {
            last = try self.emitNode(expr);
        }
        return last;
    }

    fn emitPreamble(self: *LLVMEmitter) EmitError!void {
        const arch = @import("builtin").cpu.arch;
        const os = @import("builtin").os.tag;
        const triple = switch (arch) {
            .aarch64 => switch (os) {
                .macos => "aarch64-apple-macosx",
                .linux => "aarch64-unknown-linux-gnu",
                else => "aarch64-unknown-unknown",
            },
            .x86_64 => switch (os) {
                .macos => "x86_64-apple-macosx",
                .linux => "x86_64-unknown-linux-gnu",
                else => "x86_64-unknown-unknown",
            },
            else => "unknown-unknown-unknown",
        };

        try self.print("; Generated by Kaappi Scheme LLVM backend\ntarget triple = \"{s}\"\n\n", .{triple});
        try self.write("declare ptr @kaappi_runtime_init()\n");
        try self.write("declare void @kaappi_runtime_deinit(ptr)\n");
        try self.write("declare i64 @kaappi_global_lookup(ptr, ptr, i64)\n");
        try self.write("declare i64 @kaappi_call_scheme(ptr, i64, ptr, i64)\n");
    }

    fn collectSymbols(self: *LLVMEmitter, nodes: []const *ir.Node, buf: [][]const u8, count: *usize) void {
        for (nodes) |node| {
            self.collectNodeSymbols(node, buf, count);
        }
    }

    fn collectNodeSymbols(self: *LLVMEmitter, node: *const ir.Node, buf: [][]const u8, count: *usize) void {
        switch (node.tag) {
            .global_ref => {
                if (types.isSymbol(node.data.global_ref)) {
                    const name = types.symbolName(node.data.global_ref);
                    if (!self.symbols.contains(name) and count.* < buf.len) {
                        self.symbols.put(name, {}) catch return;
                        buf[count.*] = name;
                        count.* += 1;
                    }
                }
            },
            .call => {
                self.collectNodeSymbols(node.data.call.operator, buf, count);
                for (node.data.call.args) |arg| {
                    self.collectNodeSymbols(arg, buf, count);
                }
            },
            .begin => {
                for (node.data.begin) |expr| {
                    self.collectNodeSymbols(expr, buf, count);
                }
            },
            else => {},
        }
    }

    fn emitSymbolConstants(self: *LLVMEmitter, names: []const []const u8) EmitError!void {
        if (names.len == 0) return;
        try self.write("\n");
        for (names) |name| {
            try self.print("@.sym.{s} = private unnamed_addr constant [{d} x i8] c\"{s}\"\n", .{ name, name.len, name });
        }
    }

    fn freshTemp(self: *LLVMEmitter) EmitError![]const u8 {
        const n = self.tmp_counter;
        self.tmp_counter += 1;
        const s = std.fmt.allocPrint(self.allocator, "%t{d}", .{n}) catch return error.OutOfMemory;
        return s;
    }

    fn write(self: *LLVMEmitter, s: []const u8) EmitError!void {
        self.buf.appendSlice(self.allocator, s) catch return error.OutOfMemory;
    }

    fn print(self: *LLVMEmitter, comptime fmt: []const u8, args: anytype) EmitError!void {
        const s = std.fmt.allocPrint(self.allocator, fmt, args) catch return error.OutOfMemory;
        defer self.allocator.free(s);
        try self.write(s);
    }

    pub fn toSlice(self: *LLVMEmitter) []const u8 {
        return self.buf.items;
    }
};

pub const EmitError = error{
    UnsupportedNodeType,
    OutOfMemory,
};
