;; Regression test for #54: negative index args must error, not panic

(import (scheme base) (scheme write) (srfi 13))

(define (expect-error thunk name)
  (guard (exn (#t (begin (display "PASS: ") (display name) (newline))))
    (thunk)
    (display "FAIL: ") (display name) (display " did not error") (newline)))

(expect-error (lambda () (string-take "hello" -1))
              "string-take negative")
(expect-error (lambda () (string-drop "hello" -1))
              "string-drop negative")
(expect-error (lambda () (string-take-right "hello" -1))
              "string-take-right negative")
(expect-error (lambda () (string-drop-right "hello" -1))
              "string-drop-right negative")
(expect-error (lambda () (string-pad "hello" -1))
              "string-pad negative")
(expect-error (lambda () (string-pad-right "hello" -1))
              "string-pad-right negative")
(expect-error (lambda () (string-replace "abcdef" "XY" -1 2))
              "string-replace negative start")
(expect-error (lambda () (string-replace "abcdef" "XY" 0 -1))
              "string-replace negative end")
(expect-error (lambda () (string-tabulate char-upcase -1))
              "string-tabulate negative")
(expect-error (lambda () (string-index "hello" char-alphabetic? -1))
              "string-index negative start (parseStartEnd)")
(expect-error (lambda () (string-contains "hello" "l" -1))
              "string-contains negative start (parseStartEnd)")
